### PR TITLE
register interfaces with ament index

### PR DESCRIPTION
**Pull request by dirk-thomas**
Connects to ros2/rosidl#22

@ros2/owners Please review.

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
+1

Just to be clear the contents of the file are just the names of the interfaces, but not the file ext or the path? Couldn't that cause problems with overlapping interfaces, e.g. Empty.msg and Empty.srv in the same package?

**Comment by dirk-thomas** [comment]
Therefore the content of the ament index contains the filenames including the extension.

**Comment by mikaelarguedas** [comment]
@dirk-thomas  do we still need this branch?

**Comment by dirk-thomas** [comment]
No, deleted. Thanks for pointing it out.

**Pull request merged**
