### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by wjwwood**
Fixes for compiler warnings and errors. 

Connects to ros2/ros2#9

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by dirk-thomas** [comment]
lgtm

**Comment by wjwwood** [comment]
Please have a look at 32d0441, it solves ros2/rosidl#8 for me on Windows.

**Comment by wjwwood** [comment]
The Windows CI job is green: http://54.183.26.131:8080/job/ros2_batch_ci_windows/

**Comment by dirk-thomas** [comment]
Please add a comment with the link to the MS knowledge base article above the line to describe why it is done that way.

I was surprised for a second how the job could be green. It looks like does neither compile not run any tests: https://github.com/ros2/ros2/issues/6#issuecomment-82748716

**Comment by wjwwood** [comment]
> Please add a comment with the link to the MS knowledge base article above the line to describe why it is done that way.

There's no knowledge base article, it actually just makes more sense I think. You just have to think about the elements in the vector as being initialized separately from the vector, like this:

```c++
std::vector<int> a = {-5};  // Is implicitly {{-5}}
std::vector<int> b = {-5, 5}; // Is implicitly {{-5}, {5}}
```

This is perhaps a better way to think about it:

```c++
struct A {
  int foo;
  char bar;
};

std::vector<struct A> vec = {{1, 'a'}, {2, 'b'}};
```

But in the case of single values for types which can convert to `size_t`, the Windows compiler is sort of correct because it's not clear if `vector<int>({5})` should be expanded to `vector<int>(5)` or `vector<int>({{5}})`. And the former becomes ambiguous with the third std::vector constructor because it can be converted to a `size_t`:

http://en.cppreference.com/w/cpp/container/vector/vector (constructor 3)

We're already doing this syntax for our `std::arrays`, so my patch just removes the array specific logic and wraps values in `{}` as well as a containing set of `{}` for the container structure (vector or array).

**Pull request merged**
