### PR TITLE
Don't allocate any memory for std::vector types with ZERO.

### PR DESCRIPTION
**Pull request by clalancette**
I'm still working on/testing this, but opening for visibility.

As discussed in https://github.com/ros2/rosidl/issues/251,
it makes more sense for the std::vector types to get no
items with ZERO initialization.  Change to that here.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@clalancette Is this targeted to get in before the release ?

**Comment by clalancette** [comment]
> @clalancette Is this targeted to get in before the release ?

I'm honestly not sure.  Let's discuss it and make a decision which way we want to go.

**Comment by clalancette** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3708/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/869/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3041/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3807/)

**Comment by clalancette** [comment]
This should be ready for review now.

**Comment by clalancette** [comment]
Great, thanks.  Merging.

**Pull request merged**
