### PR TITLE
Backport of #393 to dashing

### PR DESCRIPTION
**Pull request by wjwwood**
Backport of #393 to dashing, needed as noted here: https://github.com/ros2/rosidl/pull/393#issuecomment-518731893

### CODE REVIEW

**Comment by wjwwood** [comment]
CI (full, this branch, `dashing` repos file):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8073/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4080/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6579/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7945/)

**Comment by wjwwood** [comment]
CI is failing in `rviz_rendering`, what CI should I run, presuming that the dashing repo file is not compiling (my conclusion based on the fact that this patch shouldn't affect `rviz_rendering`). This is the error snippet:

```
13:01:56 CMake Error at CMakeLists.txt:42 (find_package):
13:01:56   By not providing "Findeigen3_cmake_module.cmake" in CMAKE_MODULE_PATH this
13:01:56   project has asked CMake to find a package configuration file provided by
13:01:56   "eigen3_cmake_module", but CMake did not find one.
13:01:56 
13:01:56   Could not find a package configuration file provided by
13:01:56   "eigen3_cmake_module" with any of the following names:
13:01:56 
13:01:56     eigen3_cmake_moduleConfig.cmake
13:01:56     eigen3_cmake_module-config.cmake
13:01:56 
13:01:56   Add the installation prefix of "eigen3_cmake_module" to CMAKE_PREFIX_PATH
13:01:56   or set "eigen3_cmake_module_DIR" to a directory containing one of the above
13:01:56   files.  If "eigen3_cmake_module" provides a separate development package or
13:01:56   SDK, be sure it has been installed.
13:01:56 
13:01:56 
13:01:56 -- Configuring incomplete, errors occurred!
```

The cause looks like something wrong with the patch on the dashing branch of rviz related to eigen? (https://github.com/ros2/rviz/commit/7491f8e02258a594714346f01a09753c59c8a32b) @sloretz?

**Comment by sloretz** [comment]
> The cause looks like something wrong with the patch on the dashing branch of rviz related to eigen? (ros2/rviz@7491f8e) @sloretz?

@wjwwood https://github.com/ros2/ros2/pull/773 adds `eigen3_cmake_module` to the `dashing` repos file.

**Comment by wjwwood** [comment]
CI again (full - connext, this branch, dashing repos file):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8080/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4085/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6584/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7957/)

**Comment by nuclearsandwich** [comment]
The flake8 in CI above appear don't block this backport. Fixes for the affected repositories can be made if and when they ever need other fixes in Dashing.

**Pull request merged**
