### PR TITLE
rename rosidl_generator_cpp namespace to rosidl_runtime_cpp

### PR DESCRIPTION
**Pull request by dirk-thomas**
Follow up of #442 as part of #447 to match namespace with the package the name the symbols are defined in.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Only Linux / FastRTPS with linter tests since the change shouldn't have any runtime impact (if it compiles successfully): [Build Status](https://ci.ros2.org/job/ci_linux/10090/)

Since I screwed up the arguments the linter tests didn't run. Since I need to make several more rounds of PRs for all the rosidl_generator_c/cpp API review follow ups I will go ahead and merge this (and fix linter warnings if they appear).

**Comment by dirk-thomas** [comment]
I accidentally squash merged the PR. Since the intention was to keep the two commits separate (to maintain history) I force pushed to `master` to keep them separate.

**Comment by Karsten1987** [comment]
I just updated my workspace with `vcs pull` and run into the following errors:
```
--- stderr: rosidl_runtime_c
/Users/karsten/workspace/ros2/ros2_master/src/ros2/rosidl/rosidl_runtime_c/src/service_type_support.c:15:10: fatal error: 'rosidl_generator_c/service_type_support_struct.h' file not found
#include "rosidl_generator_c/service_type_support_struct.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/karsten/workspace/ros2/ros2_master/src/ros2/rosidl/rosidl_runtime_c/src/message_bounds.c:15:10: fatal error: 'rosidl_generator_c/message_bounds_struct.h' file not found
#include "rosidl_generator_c/message_bounds_struct.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/karsten/workspace/ros2/ros2_master/src/ros2/rosidl/rosidl_runtime_c/src/message_type_support.c:15:10: fatal error: 'rosidl_generator_c/message_type_support_struct.h' file not found
/Users/karsten/workspace/ros2/ros2_master/src/ros2/rosidl/rosidl_runtime_c/src/u16string_functions.c:15:10: fatal error: 'rosidl_generator_c/u16string_functions.h' file not found
#include "rosidl_generator_c/message_type_support_struct.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#include "rosidl_generator_c/u16string_functions.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/karsten/workspace/ros2/ros2_master/src/ros2/rosidl/rosidl_runtime_c/src/string_functions.c:15:10: fatal error: 'rosidl_generator_c/string_functions.h' file not found
#include "rosidl_generator_c/string_functions.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

am I missing something here? I tried compiling with `--packages-up-to rosbag2 --cmake-clean-cache`

**Comment by dirk-thomas** [comment]
You might want to check that you have the latest master of this repo as well as all the referenced PRs. If you use a branch on any of them you will likely need to rebase it.

**Comment by emersonknapp** [comment]
The build is currently failing on a fresh checkout of master from this PR - https://ci.ros2.org/view/All/job/ci_linux/10100/console

**Comment by Karsten1987** [comment]
I don't fully grasp the dependencies here:

`rosidl_generator_c` is depending on `rosidl_runtime_c`: https://github.com/ros2/rosidl/blob/master/rosidl_generator_c/CMakeLists.txt#L16
But then, `rosidl_runtime_c` is using headers from `rosidl_generator_c`: https://github.com/ros2/rosidl/blob/master/rosidl_runtime_c/src/service_type_support.c#L15

**Comment by dirk-thomas** [comment]
> I accidentally squash merged the PR. Since the intention was to keep the two commits separate (to maintain history) I force pushed to master to keep them separate.

This was the actual problem - I was already working on the follow up patch to move the `rosidl_generator_c` headers and some changes from that slipped in the force push.

I have fixed the problem with the two recently referenced commits which only touch `rosidl_generator_cpp` as intended. See [Build Status](https://ci.ros2.org/view/All/job/ci_linux/10106/) (which is a rebuild of the minimal build @emersonknapp started above).

Sorry for the hassle.

**Comment by dirk-thomas** [comment]
> I don't fully grasp the dependencies here:
> `rosidl_generator_c` is depending on `rosidl_runtime_c`: https://github.com/ros2/rosidl/blob/master/rosidl_generator_c/CMakeLists.txt#L16
> But then, `rosidl_runtime_c` is using headers from `rosidl_generator_c`: https://github.com/ros2/rosidl/blob/master/rosidl_runtime_c/src/service_type_support.c#L15

**Comment by dirk-thomas** [comment]
> I don't fully grasp the dependencies here:
> `rosidl_generator_c` is depending on `rosidl_runtime_c`: https://github.com/ros2/rosidl/blob/master/rosidl_generator_c/CMakeLists.txt#L16
> But then, `rosidl_runtime_c` is using headers from `rosidl_generator_c`: https://github.com/ros2/rosidl/blob/master/rosidl_runtime_c/src/service_type_support.c#L15

The headers have been moved in #442 but the directory / namespace has not been updated. This PR does exactly that - update the namespace to match the package name - for the C++ generator / runtime. A similar PR for C will need to follow. All part of the API review in #446 / #447.

**Pull request merged**
