### PR TITLE
Fix python generator warnings

### PR DESCRIPTION
**Pull request by jacquelinekay**
Attempts to fix all "possible loss of data" warnings for float32, int8, int16, uint8, uint16 data types in the generated Python C bindings.

http://ci.ros2.org/job/ci_windows/1120

### CODE REVIEW

**Comment by dirk-thomas** [comment]
LGTM.

For a change like this it would be more efficient to run the CI job:
* with less rmw implementation as well as
* with less repositories

**Comment by jacquelinekay** [comment]
Yeah, earlier I was playing around with `--end-with rosidl_generator_py` and with only Opensplice. I will remember that for next time.

**Comment by dirk-thomas** [comment]
The console output already contains the same warnings, e.g. for `:\J\workspace\ci_windows\ws\build\rosidl_generator_py\rosidl_generator_py\rosidl_generator_py\msg\_float32_s.`

Does it make sense to continue the job?

**Comment by jacquelinekay** [comment]
that is strange, they appeared fixed locally. Yeah, I'll cancel it and take a look.

**Comment by jacquelinekay** [comment]
Trying again with fixes:
http://ci.ros2.org/job/ci_windows/1124

**Comment by jacquelinekay** [comment]
argh, I hadn't pushed a local change from my Windows VM so the first build didn't work

http://ci.ros2.org/job/ci_windows/1131

**Comment by jacquelinekay** [comment]
The "possible loss of data" warnings are now fixed.

**Pull request merged**
