### PR TITLE
Clean up BoundedVector

### PR DESCRIPTION
**Pull request by jwakely**
- Stop using reserved names for parameters
- Make comparison operators friends
- Remove unnecessary conversion operator

I've only done minimal testing of these changes, just checking the BoundedVector header can be included and compiled.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
> thoughts?

Nothing from me.

**Comment by jacobperron** [comment]
It's okay with me with full CI 👍

**Comment by jwakely** [comment]
I've force-pushed to fix the linter issues.

**Comment by hidmic** [comment]
Running full CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10775/)

**Comment by jwakely** [comment]
Are those CI failures due to my patch or was `master` already showing failures?

Looks like the builds are green now so I'll rebase and force-push this again.

**Comment by rotu** [comment]
Thank you so much! This makes the code tons more readable (plus some of the identifiers you've removed [were technically UB](https://en.cppreference.com/w/cpp/language/identifiers))

**Comment by jwakely** [comment]
They were indeed, that's why I removed them. As a standard library implementor I rely on reserved names being reserved, and not clashing with identifiers in user code.

**Pull request merged**
