### PR TITLE
Add enum support to ROSIDL

### PR DESCRIPTION
**Pull request by r7vme**
Adds support for enums into ROSIDL. Only `.idl` files supported.

Example

```idl
module test_msgs {
  module idl {
    typedef SomeEnum SomeEnum__3[3];

    module EnumsMessage_Enums {
      enum SomeEnum {
        ENUMERATOR1,
        ENUMERATOR2
      };
    };

    struct EnumsMessage {
      SomeEnum enum_value;

      @default (value="ENUMERATOR2")
      SomeEnum enum_default_value;

      SomeEnum__3 static_array_values;

      sequence<SomeEnum, 3> bounded_array_values;

      sequence<SomeEnum> dynamic_array_values;
    };
  };
};
```

Fixes https://github.com/ros2/rosidl/issues/260

### List of related pull requests

https://github.com/ros2/test_interface_files/pull/20
https://github.com/ros2/rosidl_python/pull/170
https://github.com/ros2/rosidl_dds/pull/58
https://github.com/ros2/rosidl_typesupport_fastrtps/pull/89

### TODO

- Add support to non-default RMWs
- Design document and documentation

### CODE REVIEW

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/need-reviewers-for-rosidl-related-change/26285/1

**Comment by methylDragon** [comment]
Hmm, CI is failing with

```
08:09:25 /tmp/ws/src/rosidl/rosidl_generator_c/test/test_interfaces.c:28:10: fatal error: rosidl_generator_c/idl/enums.h: No such file or directory
08:09:25    28 | #include "rosidl_generator_c/idl/enums.h"
```

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/why-did-ros2-keep-msg-interface-definitions/27631/2

**Comment by r7vme** [comment]
Closing as I have no plans to work on this in the near time (see more details [here](https://github.com/ros2/rosidl/issues/260#issuecomment-1310490871)).

**Pull request closed without merging**
