### PR TITLE
Instruct CMake to run the tests.

### PR DESCRIPTION
**Pull request by ernestmc**
The C tests were actually not being executed when running `ament test` so added them to `CMakeList.txt`.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can you please trigger a set of CI jobs for this branch.

**Comment by ernestmc** [comment]
Triggered CI jobs:
* http://ci.ros2.org/job/ci_linux/1060/
* http://ci.ros2.org/job/ci_osx/870/
* Windows job 1​13​0 pending because another one is in progress

**Comment by ernestmc** [comment]
The Linux build had errors building for fastrtps so I'll trigger a new job deactivating fastrtps:
http://ci.ros2.org/job/ci_linux/1060/console#console-section-23

* http://ci.ros2.org/job/ci_linux/1062/

**Comment by dirk-thomas** [comment]
I installed Boost program options on the Linux machine since it is a new dependency of FastRTPS: https://github.com/eProsima/Fast-RTPS/commit/ca6d226bbdae58bebcf3a26953fd20c04dff8871#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by ernestmc** [comment]
@dirk-thomas thanks for the notice.
Build was good and tests are working. Once I get approval I'll proceed to merge it.

```
17:23:15 Test project /home/rosbuild/ci_scripts/ws/build/rosidl_generator_c
17:23:15 Constructing a list of tests
17:23:15 Checking test dependency graph...
17:23:15 Checking test dependency graph end
17:23:15 test 1
17:23:15       Start  1: test_compilation_c
17:23:15 
17:23:15 1: Test command: /home/rosbuild/ci_scripts/ws/build/rosidl_generator_c/test_compilation_c
17:23:15 1: Test timeout computed to be: 9.99988e+06
17:23:15 1: all checks passed
17:23:15  1/10 Test  #1: test_compilation_c ...............   Passed    0.00 sec
17:23:15 test 2
17:23:15       Start  2: test_interfaces_c
17:23:15 
17:23:15 2: Test command: /home/rosbuild/ci_scripts/ws/build/rosidl_generator_c/test_interfaces_c
17:23:15 2: Test timeout computed to be: 9.99988e+06
17:23:15 2: Testing rosidl_generator_c message types...
17:23:15 2: Testing simple primitive message types...
17:23:15 2: Testing simple primitives with default values...
17:23:15 2: Testing string types...
17:23:15 2: Testing primitives unbounded arrays types...
17:23:15 2: Testing primitives bounded arrays types...
17:23:15 2: Testing primitives static arrays types...
17:23:15 2: Testing nested sub-messages...
17:23:15 2: All tests were good!
17:23:15  2/10 Test  #2: test_interfaces_c ................   Passed    0.00 sec
17:23:15 test 3
17:23:15       Start  3: copyright
```

**Comment by dirk-thomas** [comment]
+1

Please assign the ticket to yourself to make that visible in waffle.

**Pull request merged**
