### PR TITLE
change .template into .em

### PR DESCRIPTION
**Pull request by dirk-thomas**
CI still passing: http://ci.ros2.org/job/ci_linux/1299/

### CODE REVIEW

**Comment by dirk-thomas** [comment]
And another round with the templates using indentation to make the logic more readable: http://ci.ros2.org/job/ci_linux/1301/

**Comment by dirk-thomas** [comment]
Please review.

**Comment by mikaelarguedas** [comment]
lgtm +1

**Comment by mikaelarguedas** [comment]
@dirk-thomas  do we still need this branch?

**Comment by dirk-thomas** [comment]
No, deleted. Thanks for pointing it out.

**Pull request merged**
