### PR TITLE
Pull Request for adding scope keywords feature in rosidl_target_interfaces  (Issue#400)

### PR DESCRIPTION
**Pull request by FahadRazaKhan**
This PR is for the **issue#400** "_Using rosidl_target_interfaces incompatible with keyword target_link_libraries command_".  As _rosidl_target_interfaces_ did not have the scope keyword options it could become incompatible with the _target_link_libraries_ command if used with a scope keyword.

### CODE REVIEW

**Comment by FahadRazaKhan** [comment]
Do I need to sign-off my commit?

**Comment by clalancette** [comment]
> Do I need to sign-off my commit?

Yes.

Besides that, please remove other changes to this PR that don't directly have to do with the issue you are trying to fix.  It makes it difficult to review and see what is actually being changed.

**Comment by FahadRazaKhan** [comment]
@clalancette Thanks for the feedback. For the sign-off, should I rebase my branch or is it unsafe?
The other changes I did not incorporate, I believe these changes just appeared because of syncing with the latest branch.

**Comment by FahadRazaKhan** [comment]
@clalancette I have removed the other changes. Can you please review. Thanks.

**Review by fujitatomoya — COMMENTED** [review]
lgtm with green CI.

Note, can we add scope keywords are optionally supported in the doc section?

**Comment by FahadRazaKhan** [comment]
@clalancette and @fujitatomoya any update?

**Comment by fujitatomoya** [comment]
> Note, can we add scope keywords are optionally supported in the doc section?

im sorry, bad memory 😓  I think what i mean was to add an explanation in function doc header, line 22 -

**Comment by FahadRazaKhan** [comment]
@fujitatomoya thank you for your explanation. I have added a few comments in the doc header as you suggested. Please have a review.

**Comment by FahadRazaKhan** [comment]
@fujitatomoya just a reminder that I have updated the doc header.

**Comment by FahadRazaKhan** [comment]
@clalancette Hi, it's been a month since I updated the PR. I believe @fujitatomoya  is busy so can someone else review and approve it please?

**Review by fujitatomoya — APPROVED** [review]
sorry for being late to get back.

lgtm, i would like to have another review.

**Comment by FahadRazaKhan** [comment]
@fujitatomoya any update? are you asking someone else for another review?

**Comment by fujitatomoya** [comment]
@clalancette @sloretz can you have a look when you have time?

**Comment by FahadRazaKhan** [comment]
@clalancette @sloretz @fujitatomoya guys this is a long pending PR. Would you please give it a final review and accept for merge. Thanks.

**Comment by sloretz** [comment]
Thank you for the PR and patience @FahadRazaKhan . The bad news is I don't think we should take this PR because this method [has been deprecated for three years](https://github.com/ros2/rosidl/pull/606). The good news is there's already a solution to the problem you described that you can use today.

Say you want to use C++ messages from the same package, and you have a line like this:

```Cmake
rosidl_target_interfaces(target_name ${PROJECT_NAME} "rosidl_typesupport_cpp")
```

Change it to this

```Cmake
  rosidl_get_typesupport_target(cpp_typesupport_target ${PROJECT_NAME} "rosidl_typesupport_cpp")
  target_link_libraries(target_name PRIVATE "${cpp_typesupport_target}")
```

See this PR for a real example: https://github.com/ros2/common_interfaces/pull/156/files

**Pull request closed without merging**
