### PR TITLE
fix inconsistent dll linkage

### PR DESCRIPTION
**Pull request by dirk-thomas**
Before: http://ci.ros2.org/job/ci_windows/1118/
After: http://ci.ros2.org/job/ci_windows/1126/

### CODE REVIEW

**Comment by wjwwood** [comment]
lgtm

**Comment by jacquelinekay** [comment]
The "inconsistent dll linkage" warnings are still present in job 1126:

http://ci.ros2.org/job/ci_windows/1126/warnings34Result/package.553556865/
http://ci.ros2.org/job/ci_windows/1126/warnings34Result/package.1446163859/file.1470454761/
http://ci.ros2.org/job/ci_windows/1126/warnings34Result/package.1446163859/file.1470454761/

**Comment by dirk-thomas** [comment]
That's why this is still "in progress" :wink:

**Comment by jacquelinekay** [comment]
That's what I thought :P

**Comment by jacquelinekay** [comment]
@dirk-thomas, if you're too busy to finish this, I could take a look--I have an idea for eliminating these warnings.

**Comment by dirk-thomas** [comment]
Sure, go ahead. I am busy with ROS 1 tickets arm.

**Comment by jacquelinekay** [comment]
Rebuilding with a tweak:
http://ci.ros2.org/job/ci_windows/1146

I think the warnings will be gone, but it can be hard to tell locally because of the small command line history in VS Developer Command Prompt...

**Comment by wjwwood** [comment]
A trick I use is to pipe the build to a file and then open it in an editor.

**Comment by jacquelinekay** [comment]
well, my change fixed some warnings and created new ones in other places...

**Comment by jacquelinekay** [comment]
I believe I understand the issue now.

The forward declaration of the `ROSIDL_GET_TYPE_SUPPORT_FUNCTION(message_pkg, msg, message_type)()` function was the source of the error.

Rebuilding again: http://ci.ros2.org/job/ci_windows/1148

**Comment by jacquelinekay** [comment]
The above build has no warnings. Should I trigger a normal build just in case (using all repos/middleware impls)?

**Comment by dirk-thomas** [comment]
The recent build looks very promising. But yes, please trigger a full build of this - even for all platforms.

**Comment by jacquelinekay** [comment]
http://ci.ros2.org/job/ci_linux/1085/
http://ci.ros2.org/job/ci_osx/878/
http://ci.ros2.org/job/ci_windows/1151/

**Comment by jacquelinekay** [comment]
Linux and OSX are clean, and the only warnings on Windows are due to Boost and rmw_fastrtps_cpp:

http://ci.ros2.org/job/ci_windows/1151/warnings34Result/

**Comment by dirk-thomas** [comment]
Nice, +1

Should I squash and merge or do you want to?

**Comment by jacquelinekay** [comment]
I am on it

**Pull request merged**
