### PR TITLE
Add namespaced ALIAS target to easily consume generated libraries via add_subdirectory

### PR DESCRIPTION
**Pull request by traversaro**
A common practice in "modern" CMake development practices is to always add a namespaced `ALIAS` target for each library that is installed with a given namespace, to ensure that the library can be consumed as `target_link([...] <pkg>::<target_name>)` both if the project is used via `find_package(<pkg>)` or via `FetchContent/add_subdirectory` . For more details on this, see (among other resources):
* https://cliutils.gitlab.io/modern-cmake/chapters/install.html
* https://www.youtube.com/watch?v=bsXLMQ6WgIk&t=3126s

I was trying to follow this practice in an existing project that was creating a type support library via rosidl, see  https://github.com/robotology-playground/yarp-ros2/pull/10 . By doing so, I noticed that if I included the library via `add_subdirectory` the created target was named `map2d_nws_ros2_msgs__rosidl_typesupport_cpp`, while if I was including the project via `find_package` the target was named `map2d_nws_ros2_msgs::map2d_nws_ros2_msgs__rosidl_typesupport_cpp`. As a workaround, I simply added the alias myself, as in:
~~~
if(NOT TARGET map2d_nws_ros2_msgs::map2d_nws_ros2_msgs__rosidl_typesupport_cpp)
    add_library(map2d_nws_ros2_msgs::map2d_nws_ros2_msgs__rosidl_typesupport_cpp ALIAS map2d_nws_ros2_msgs__rosidl_typesupport_cpp)
  endif()
~~~

However, I looked of how we could avoid to have such boilerplate, given that differently for most `ament_cmake` projects, this targets are not added explicitly by the project with an `add_library` call that makes it clear what is the target name, but the `add_library` is happening inside the rosidl macro. For this reason, I think it could be useful if the alias target could be added directly by the rosidl macros. I initially tried to check if this could be done at the `ament_cmake` level (see https://github.com/ament/ament_cmake/pull/349), but this turned out not be easy to do.

### CODE REVIEW

**Comment by RFRIEDM-Trimble** [comment]
Anything holding this back? We would love to use target_link_libraries with 100% alias targets so we can specify PUBLIC and PRIVATE, but are blocked by rosidl not supporting it.

**Review by sloretz — APPROVED** [review]
LGTM with green CI

**Comment by sloretz** [comment]
CI ([repos file](https://gist.githubusercontent.com/sloretz/cfe508bbc6e8f466d7ab59a2710e9395/raw/7a0d725262774dfd2c51d4c48dd67feccee224e9/ros2.repos) build: ` --packages-above-and-dependencies rosidl_generator_c rosidl_generator_cpp rosidl_typesupport_introspection_c rosidl_typesupport_introspection_cpp` test: `--packages-select rosidl_generator_c rosidl_generator_cpp rosidl_typesupport_introspection_c rosidl_typesupport_introspection_cpp test_msgs geometry_msgs std_msgs`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16950/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11515/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17349/)

**Comment by sloretz** [comment]
Thanks for the PR!

**Comment by traversaro** [comment]
Thanks for merging!

**Comment by RFRIEDM-Trimble** [comment]
This is awesome thanks! Is there a way to get this into Humble too considering it doesn't break public API, only adds a new target name?

**Comment by sloretz** [comment]
> This is awesome thanks! Is there a way to get this into Humble too considering it doesn't break public API,

Yeah, I think this is backportable to Humble

@mergifyio backport humble

**Comment by sloretz** [comment]
@mergifyio backport humble

**Comment by RFRIEDM-Trimble** [comment]
Can it also be backported to galactic before it's EOL? :pray:

**Pull request merged**
