### PR TITLE
Set CXX standard to 17

### PR DESCRIPTION
**Pull request by oysstu**
Set CXX standard to 17. Valid for Galactic and later (#634).

### CODE REVIEW

**Review by sloretz — APPROVED** [review]
I'd rather this used `target_compile_features(target_name PUBLIC cxx_std_17)` instead, but I'd treat that as an enhancement rather than blocking this PR.


LGTM with green CI

**Comment by sloretz** [comment]
CI
 * repos: `https://gist.githubusercontent.com/sloretz/6afda0358f48c644a0d292aae353e449/raw/e2f14016b0815e8c89af6233752f9a1cee1b8320/ros2.repos`
 * build: ` --packages-up-to rosidl_runtime_c rosidl_runtime_c rosidl_typesupport_introspection_cpp rosidl_typesupport_interface rosidl_runtime_cpp rosidl_generator_cpp`
 * test: `--packages-select rosidl_runtime_c rosidl_runtime_c rosidl_typesupport_introspection_cpp rosidl_typesupport_interface rosidl_runtime_cpp rosidl_generator_cpp`)
 
Jobs
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15655/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10333/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13321/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15876/)

**Review by aprotyas — CHANGES_REQUESTED** [review]
Thank you for the PR! This looks good to me on a first pass, I think you missed one instance in [`rosidl_typesupport_introspection_cpp_generate_interfaces.cmake#L101`](https://github.com/oysstu/rosidl/blob/9c24e0e13b56f176eaa1c0c774b74529b06f004a/rosidl_typesupport_introspection_cpp/cmake/rosidl_typesupport_introspection_cpp_generate_interfaces.cmake#L101)

```cmake
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  set_target_properties(${rosidl_generate_interfaces_TARGET}${_target_suffix} PROPERTIES
    CXX_STANDARD 14
    COMPILE_OPTIONS -Wall -Wextra -Wpedantic
  )
```

**Comment by aprotyas** [comment]
The warnings in the MSVC build come from the deprecation of [`std::wstring_convert`](https://en.cppreference.com/w/cpp/locale/wstring_convert) and of the [`<codecvt>`](https://en.cppreference.com/w/cpp/header/codecvt) header in C++17.

The deprecation message isn't benign because:
```
The C++ Standard doesn't provide equivalent non-deprecated functionality; consider using MultiByteToWideChar() and WideCharToMultiByte() from instead.
```

The suggestion here is not portable, being part of the Win32 API.

---

There's a couple of ways to approach this:

- According to https://isocpp.org/files/papers/p0636r0.html, the recommendation is "Users should use dedicated text-processing libraries instead."
  - [utfcpp](https://github.com/nemtrif/utfcpp) is a good library to do so, but that would introduce an external dependency in a core package.
- Silence this specific deprecation warning with `#define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING` and hope that said classes/header are not removed before proper Unicode support is added to C++23.

**Comment by oysstu** [comment]
> I'd rather this used `target_compile_features(target_name PUBLIC cxx_std_17)` instead, but I'd treat that as an enhancement rather than blocking this PR.
> 
> LGTM with green CI

Yes, that seems to be the modern approach to setting the C++ standard. Would also require upping the minimum cmake version to 3.10 in order to have support for MSVC. This is also a change that could be applied to all c++ packages.

> Thank you for the PR! This looks good to me on a first pass, I think you missed one instance in
> ...

Nice catch, I've pushed another commit that changes this one as well.

> The warnings in the MSVC build come from the deprecation of [`std::wstring_convert`](https://en.cppreference.com/w/cpp/locale/wstring_convert) and of the [`<codecvt>`](https://en.cppreference.com/w/cpp/header/codecvt) header in C++17 - these are used in [`rosidl_runtime_cpp/traits.hpp`](https://github.com/ros2/rosidl/blob/master/rosidl_runtime_cpp/include/rosidl_runtime_cpp/traits.hpp).
> ...
According to the deprecation statement, the codecvt _"library component should be retired to Annex D, along side , until a suitable replacement is standardized"_ . I guess this means that it won't be removed for a long time.

**Comment by aprotyas** [comment]
> According to the deprecation statement, the codecvt _"library component should be retired to Annex D, along side , until a suitable replacement is standardized"_. I guess this means that it won't be removed for a long time.

In the spirit of not fixing what isn't broken, I propose this deprecation be silenced with the `_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING` macro. It looks like @clalancette has a working branch that achieves this, check https://github.com/ros2/rosidl/commit/0c283d0db26c0c73f76aa20f624b0510c8766c5b.

```cmake
if(MSVC)
  ament_export_definitions(_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING)
endif()
```

**Comment by aprotyas** [comment]
> Should I merge that branch into this PR?

Sure - you could also cherry-pick https://github.com/ros2/rosidl/commit/8f855b72f6a53cf90e5762a801442b947f79c43b and https://github.com/ros2/rosidl/commit/0c283d0db26c0c73f76aa20f624b0510c8766c5b onto your working branch. That might be less friction than a merge.

**Review by aprotyas — APPROVED** [review]
Thanks for iterating! LGTM with green CI.

Rerunning CI from above:
 * repos: `https://gist.githubusercontent.com/sloretz/6afda0358f48c644a0d292aae353e449/raw/e2f14016b0815e8c89af6233752f9a1cee1b8320/ros2.repos`
 * build: ` --packages-up-to rosidl_runtime_c rosidl_runtime_c rosidl_typesupport_introspection_cpp rosidl_typesupport_interface rosidl_runtime_cpp rosidl_generator_cpp`
 * test: `--packages-select rosidl_runtime_c rosidl_runtime_c rosidl_typesupport_introspection_cpp rosidl_typesupport_interface rosidl_runtime_cpp rosidl_generator_cpp`
 
Jobs
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15668/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10346/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13330/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15892/)

**Comment by aprotyas** [comment]
It looks like MSVC throws the deprecation warnings despite https://github.com/ros2/rosidl/pull/635/commits/7ec237ede2b345e1edd4748452d774c05bbb9c5d. I'm not sure how the definition exporting mechanics is supposed to work. Any clues? May just have to define the silencing macro in the [`rosidl_runtime_cpp/traits.hpp`](https://github.com/ros2/rosidl/blob/master/rosidl_runtime_cpp/include/rosidl_runtime_cpp/traits.hpp) header.

**Comment by oysstu** [comment]
> It looks like MSVC throws the deprecation warnings despite [7ec237e](https://github.com/ros2/rosidl/commit/7ec237ede2b345e1edd4748452d774c05bbb9c5d). I'm not sure how the definition exporting mechanics is supposed to work. Any clues? May just have to define the silencing macro in the [`rosidl_runtime_cpp/traits.hpp`](https://github.com/ros2/rosidl/blob/master/rosidl_runtime_cpp/include/rosidl_runtime_cpp/traits.hpp) header.

I don't think the 'ament_export_definitions' macro adds the preprocessor definition at all, it seems like it may have something to do with exporting definitions to downstream packages, but I can't find any documentation. For now, I think it's best to simply use add_compile_options (ROS hasn't begun to use the modern target-specific cmake style as far as I know). Not sure how this affects other packages that include this header, I'm not that familiar with the ament_cmake machinery (perhaps this is what ament_export_definitions does).

Defining it in the header isn't a good option, as it needs to be defined before the STL libraries are pulled in ([https://devblogs.microsoft.com/cppblog/c17-feature-removals-and-deprecations/](https://devblogs.microsoft.com/cppblog/c17-feature-removals-and-deprecations/)). 

e.g.
```C++
if (MSVC)
    add_compile_options(_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING)
endif()```

**Comment by aprotyas** [comment]
> ROS hasn't begun to use the modern target-specific cmake style as far as I know

Every PR can be a small step in that direction! ;-)

> Defining it in the header isn't a good option, as it needs to be defined before the STL libraries

Understood. Since `add_compile_options` appends to the project-scope `COMPILE_OPTIONS` variable, it might be better to limit the scope of the compile definition to direct consumers as such?

```cmake
if(MSVC)
  target_compile_definitions(${PROJECT_NAME} INTERFACE
  _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING)
endif()
```

**Comment by oysstu** [comment]
Ok, I've added the proposed change and rebased/squashed the commits. Hopefully the current change successfully disables the warning on MSVC.

**Comment by aprotyas** [comment]
Thanks for iterating @oysstu! There's a linter error in the CMakeLists.txt file, I think replacing `if (MSVC)` with `if(MSVC)` should fix it. Can you commit that change and then I'll run CI again?

**Comment by aprotyas** [comment]
Rerunning CI:
 * repos: `https://gist.githubusercontent.com/sloretz/6afda0358f48c644a0d292aae353e449/raw/e2f14016b0815e8c89af6233752f9a1cee1b8320/ros2.repos`
 * build: ` --packages-up-to rosidl_runtime_c rosidl_runtime_c rosidl_typesupport_introspection_cpp rosidl_typesupport_interface rosidl_runtime_cpp rosidl_generator_cpp`
 * test: `--packages-select rosidl_runtime_c rosidl_runtime_c rosidl_typesupport_introspection_cpp rosidl_typesupport_interface rosidl_runtime_cpp rosidl_generator_cpp`
 
Jobs
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15718/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10400/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13383/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15962/)

**Comment by hidmic** [comment]
@aprotyas @clalancette shall we get this moving?

**Comment by aprotyas** [comment]
I think this PR is ready to go, feel free to merge it please!

**Comment by hidmic** [comment]
It's been a while. Running full CI to be on the safe side:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15876/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10553/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13542/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16179/)

**Comment by aprotyas** [comment]
Test failures look unrelated. The windows test failure is reported as flaky.

**Comment by hidmic** [comment]
> Test failures look unrelated. The windows test failure is reported as flaky.

Indeed. Going in. Thanks @oysstu !

**Pull request merged**
