### PR TITLE
Consolidate C code of Python extensions

### LINKED ISSUE #96: Look into generating only one Python library per message package
This may reduce compilation time and also simplify our CMake scripts.

### PR DESCRIPTION
**Pull request by esteve**
Consolidate Python extensions into one per package and per type support implementation

Fixes #96

### CODE REVIEW

**Comment by esteve** [comment]
CI:

http://ci.ros2.org/job/ci_linux/1031/
http://ci.ros2.org/job/ci_osx/850/
http://ci.ros2.org/job/ci_windows/1090/

**Comment by esteve** [comment]
OSX fails, looking into that.

**Comment by esteve** [comment]
And Windows too.

**Comment by esteve** [comment]
Latest CI:

http://ci.ros2.org/job/ci_linux/1033/
http://ci.ros2.org/job/ci_osx/854/
http://ci.ros2.org/job/ci_windows/1097/ (fails)

**Comment by esteve** [comment]
Closing and deleting this, it wasn't leading to any meaningful improvement and was left to die.

**Comment by jacquelinekay** [comment]
thanks @esteve. May this deleted branch rest in peace. Let me know if you want more active review on any other PRs you have pending.

**Pull request closed without merging**
