### PR TITLE
Revert "Registers IDL interfaces' subfolders with Ament."

### PR DESCRIPTION
**Pull request by mjcarroll**
This reverts commit 7d791728f36b99f08242aedd33aac05f95c64619.

This should address recent failures in the build farm with regards to `ros1_bridge`, where the dynamic bridge could not match messages due to the change in the way they were registered.

For example: https://ci.ros2.org/view/packaging/job/packaging_linux/1254/

### CODE REVIEW

**Comment by mjcarroll** [comment]
Linux: https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=143
Windows: https://ci.ros2.org/buildStatus/icon?job=ci_packaging_windows&build=81

**Comment by hidmic** [comment]
@mjcarroll there's just one small issue with this: tests in the `system_tests/test_communication` package will run for the messages and services that underpin actions, which is not intended and not supported as it was stated [here](https://github.com/ros2/system_tests/pull/303#pullrequestreview-169578958).

**Comment by hidmic** [comment]
I wonder how big's the gap to fill in order to make `ros1_bridge` pass again.

**Comment by sloretz** [comment]
Just remembered ros2/ros2cli#153 would also need a PR if this is reverted. I imagine the inverse, updating ros1_bridge, would be close to that PR.

**Comment by mjcarroll** [comment]
@dirk-thomas Do you have any objection to just fixing up ros1_bridge in this case?

**Comment by dirk-thomas** [comment]
I don't mind how it gets fixed for now.

**Comment by mjcarroll** [comment]
We opted to fix this in ros1_bridge: https://github.com/ros2/ros1_bridge/pull/143

**Pull request closed without merging**
