### PR TITLE
refactor generated PyInit function

### PR DESCRIPTION
**Pull request by dirk-thomas**
@mikaelarguedas How does this look?

For each type a separate internal function is generated. The three capsules for each type are generated in a loop.

I only explicitly decrement capsules that are not successfully added to the module since the assumption is that the module will remove all previously added objects when it is being destroyed.

Extending #126.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
looks good to me, you may want to clean up the now unused logic and variables (e.g. `pymodule_list`)

**Comment by dirk-thomas** [comment]
Good point. Gone.

**Comment by mikaelarguedas** [comment]
I don't know if it has it's place in this PR but a test to confirm that there is no memory leak and that all objects are actually DECREFed and collected by GC at module destruction would be sweet. It's kind of a one time test but we would want to test it on all platforms before actually merging it on master.

Otherwise +1

**Comment by dirk-thomas** [comment]
Since there was no such test before I would not block this PR and the others on that.

**Comment by mikaelarguedas** [comment]
Makes sense. Ready for merge then

**Pull request merged**
