### PR TITLE
[dashing backport] support adjacent string literals

### PR DESCRIPTION
**Pull request by jacobperron**
Backporting #411 and #410

### CODE REVIEW

**Comment by jacobperron** [comment]
@TSC21 FYI

**Comment by jacobperron** [comment]
Up to `test_msgs` and `test_communication`:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8355/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4286/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6810/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8258/)

**Comment by TSC21** [comment]
Excellent! Thank you very much @jacobperron!

**Comment by TSC21** [comment]
@nuclearsandwich any reason why this was moved from the Patch Release 4 to 5? This is current a development blocker...

**Pull request merged**
