### PR TITLE
fix generated C code to actually compile

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by ernestmc** [comment]
@dirk-thomas I had opened issue #46 for the test cases and was working on it. I don't wan't to overlap with you so should I close it?

**Comment by dirk-thomas** [comment]
I didn't know that you are already working on it since the ticket is neither assigned nor in-progress. Since I need the generated C code to be compilable in order to work on the typesupport for it I just started on this.

I have updated this PR to only perform the necessary stuff to generate message and compile against them (with a dummy empty message).

I am mainly interested in compilable code. I wouldn't bother with tests for now. So it would be great if you can continue to work on them. Let's talk offline what you already have and how to parallelize best.

**Comment by dirk-thomas** [comment]
With the latest commit (e337216e218eac45074470b5525081bdfd6f6d8c) I was at least able to compile the message definitions available in `rosidl_generator_cpp`. No guarantees about runtime behavior by now though.

Next step for me will be considering what to use for string / array data structures in C.

**Comment by dirk-thomas** [comment]
Please review.

**Comment by wjwwood** [comment]
lgtm

**Comment by wjwwood** [comment]
The Windows nightly builds are failing to compile because it complains:

From: http://ci.ros2.org/job/ros2_batch_ci_windows_nightly/102/console
```
C:\Jenkins\workspace\ros2_batch_ci_windows_nightly\workspace\build\rosidl_generator_c\rosidl_generator_c\rosidl_generator_c/msg/empty__struct.h(20): error C2016: C requires that a struct or union has at least one member
```

Just so you're aware for your next set of patches. Or maybe it should be addressed in https://github.com/ros2/rosidl/pull/51

**Comment by dirk-thomas** [comment]
That seems to be the case with C99 on Windows. I fixer it in cdf919adad38838c6494dd55ed02104d11906461 (http://ci.ros2.org/job/ros2_batch_ci_windows/670/).

**Pull request merged**
