### PR TITLE
Revert "Make rosidl packages use FindPython3 instead of FindPythonInterp (#612)"

### PR DESCRIPTION
**Pull request by mjcarroll**
This reverts commit 36ed120f43daeaab31fd9ba2bf8dfb58db05091d.

### CODE REVIEW

**Comment by clalancette** [comment]
I'm going to suggest that we run a full CI here, particularly on Windows.

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15035/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9772/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12725/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15199/)

**Comment by mjcarroll** [comment]
> I'm going to suggest that we run a full CI here, particularly on Windows.

Full CI: 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15036/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9773/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12726/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15200/)

**Comment by sloretz** [comment]
Alternative to reverting: https://github.com/ros2/rosidl_typesupport/pull/118

**Pull request closed without merging**
