### PR TITLE
[dashing] refactor regex for valid package/field names (#508)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #508 to Dashing.

### CODE REVIEW

**Review by sloretz — APPROVED** [review]

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13099/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8036/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10814/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13075/)

**Comment by jacobperron** [comment]
oof, that's a lot of linter failures. There's some test_communication failures buried in there too. @nuclearsandwich can you confirm if all of this is expected?

**Comment by nuclearsandwich** [comment]
> oof, that's a lot of linter failures.

Yeah I recommend running Dashing CI with linters turned off. Even then it won't catch everything because not all linters are properly tagged. (Somewhere I have a patch to fix that...) failures in cyclonedds aren't blocking since it's not a tier 1 rmw in Dashing.

**Comment by nuclearsandwich** [comment]
Merging this to make a release.

**Pull request merged**
