### PR TITLE
better memory handling for sequences

### PR DESCRIPTION
**Pull request by rotu**
1) don't leak memory if resized to 0
2) realloc instead of dealloc/malloc

### CODE REVIEW

**Comment by mjcarroll** [comment]
Signoff for DCO please!

**Comment by rotu** [comment]
@mjcarroll DCO'd

**Comment by dirk-thomas** [comment]
I would assume the same applies to other C functions ending in `_init()`. They are simply not supposed to be called again (without `fini` in between).

If we want to support this use case we should probably update all similar functions as well as describe this in the docblock of the API.

**Comment by mjcarroll** [comment]
@rotu Do you have a chance to address the feedback from @dirk-thomas?  It would be ideal to get this updated across the board.

**Comment by rotu** [comment]
Closing this PR. I’m not sure realloc is a good idea since it doesn’t guarantee memory alignment like malloc does

**Pull request closed without merging**
