### PR TITLE
[Galactic] backport both #584 and #590

### PR DESCRIPTION
**Pull request by sloretz**
PRS #584 and #590 need to be backported together. This PR should be rebase & merged, not squashed.

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by sloretz** [comment]
CI (branch: `galactic_backport_584_590` repos: `https://raw.githubusercontent.com/ros2/ros2/galactic/ros2.repos` rosdistro: `galactic` build: `--packages-above-and-dependencies  rosidl_generator_c  rosidl_runtime_c` test: `--packages-above rosidl_generator_c  rosidl_runtime_c`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14901/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9644/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12570/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15056/)

**Comment by sloretz** [comment]
I don't know why all CI jobs failed with this change on `projectroot.test_action_communication__rmw_cyclonedds_cpp`. I don't see that failure in the Galactic CI job: https://build.ros2.org/view/Gci/job/Gci__nightly-release_ubuntu_focal_amd64/

Maybe something more needs to be backported?

**Comment by pablogs9** [comment]
Any update?

**Comment by russkel** [comment]
We need[ed] this backport. I had to recompile the entire set of interfaces with this as a part of our project uses a custom allocator.

**Comment by sloretz** [comment]
Another go at CI

CI (branch: `galactic_backport_584_590` repos: `https://raw.githubusercontent.com/ros2/ros2/galactic/ros2.repos` rosdistro: `galactic` OS: `focal` build: `--packages-above-and-dependencies  rosidl_generator_c  rosidl_runtime_c` test: `--packages-above rosidl_generator_c  rosidl_runtime_c`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16647/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11229/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17044/)

**Comment by sloretz** [comment]
Same CI failure, and [I still don't see it on the nightly](https://build.ros2.org/view/Gci/job/Gci__nightly-release_ubuntu_focal_amd64/). I don't have the bandwidth to investigate further.

@pablogs9 @russkel If you'd like to see these backported, please consider investigating why these backports cause [projectroot.test_action_communication__rmw_cyclonedds_cpp](https://ci.ros2.org/job/ci_linux/16647/testReport/junit/(root)/projectroot/test_action_communication__rmw_cyclonedds_cpp/) to fail. I don't think this can be backported to Galactic until that's resolved.

I'll close this PR for now.

**Comment by pablogs9** [comment]
@sloretz 

>  I don't think this can be backported to Galactic until that's resolved.

I agree with you but is it necessary to close the PR and remove the backport branch?

I neither have the bandwidth to investigate this rmw_cyclonedds failure, but IMHO we should keep this open in order to ensure that it will be investigated by someone at some point during the Galactic lifetime.

**Comment by sloretz** [comment]
> IMHO we should keep this open in order to ensure that it will be investigated by someone at some point during the Galactic lifetime.

I worry leaving it open would stop someone else from taking it up because they think it's already being worked on. I don't intend to work on this PR again. 

The branch can be created again with these commands:

```
git checkout galactic
git checkout -b galactic_backport_584_590
git cherry-pick -s 44105c65b545401ea912abce2fa91ae2d7832496 608761cd1bcf6f01e4d25f8fcc9745f1ea41d0b0
```

**Comment by russkel** [comment]
For what it's worth I have been using those 2 PRs backported and it is working fine. I don't have time to debug a test in a RMW I don't use or have any experience with.

**Pull request closed without merging**
