### PR TITLE
Protect rosidl_target_interfaces from using NOTFOUND in include_directories (Humble)

### PR DESCRIPTION
**Pull request by j-rivero**
Backport of #679 for Humble

### CODE REVIEW

**Comment by Blast545** [comment]
Full Humble CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16723/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11303/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17118/)

**Comment by clalancette** [comment]
Rebuild of CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16777/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11358/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17180/)

**Comment by Blast545** [comment]
Windows had flaky `SEH: exception` failures. Re building Windows:
[Build Status](https://ci.ros2.org/job/ci_windows/17184/)

**Comment by Blast545** [comment]
Re building to avoid merging with red windows.

Windows: [Build Status](https://ci.ros2.org/job/ci_windows/17191/)

**Comment by Blast545** [comment]
Green CI + reviewer, merging.

**Pull request merged**
