### PR TITLE
Revert "add to_yaml() function for C++ messages (#523)"

### PR DESCRIPTION
**Pull request by dabonnie**
This reverts commit aac71e5f5d4ea3e48809bc9978549463dba4ab4d.

This resolves https://github.com/ros2/rosidl/issues/524

### CODE REVIEW

**Comment by dabonnie** [comment]
@dirk-thomas @ivanpauno please take a look.

**Comment by dabonnie** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12267/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7241/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9985/)
* Windows [Build Status]

**Review by sloretz — APPROVED** [review]

**Review by dirk-thomas — APPROVED** [review]

**Comment by dirk-thomas** [comment]
This can be merged without waiting for CI. It clearly fixes the regression.

I will open a redo PR for it.

**Comment by sloretz** [comment]
> This can be merged without waiting for CI. It clearly fixes the regression.

Merging. Looks like the Windows job got stuck anyways :(

https://ci.ros2.org/job/ci_windows/12157/console

**Pull request merged**
