### PR TITLE
Fix rosidl warnings

### PR DESCRIPTION
**Pull request by esteve**

### CODE REVIEW

**Comment by esteve** [comment]
CI:

http://ci.ros2.org/job/ci_linux/828/
http://ci.ros2.org/job/ci_osx/691/
http://ci.ros2.org/job/ci_windows/876/

**Comment by gerkey** [comment]
+1

**Comment by wjwwood** [comment]
lgtm too

**Comment by dirk-thomas** [comment]
The modified `test_interfaces.c` file still seems to have 6 compiler warning in the referenced Windows job.

**Pull request merged**
