### PR TITLE
[Foxy] backport both #584 and #590

### PR DESCRIPTION
**Pull request by sloretz**
PRS #584 and #590 need to be backported together. This PR should be rebase & merged, not squashed.

### CODE REVIEW

**Comment by pablogs9** [comment]
Thanks @sloretz!

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by sloretz** [comment]
CI (branch: `foxy_backport_584_590` repos: `https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos` rosdistro: `foxy` build: `--packages-above-and-dependencies  rosidl_generator_c  rosidl_runtime_c` test: `--packages-above rosidl_generator_c  rosidl_runtime_c`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14900/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9643/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12569/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15055/)

**Comment by jacobperron** [comment]
@sloretz Friendly ping. I'm preparing to do a Foxy patch release on Thursday. Let me know if you'd like to try and get this in.

**Comment by pablogs9** [comment]
Any update?

**Comment by jacobperron** [comment]
Re-triggering CI, since it's been a while: 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15633/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10314/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13301/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15852/)

**Comment by pablogs9** [comment]
Should we change something to fix those `unstable` flags?

**Comment by jacobperron** [comment]
It appears so. I triggered a build with the same flags for mainline Foxy and don't see the same test failure:

[Build Status](https://ci.ros2.org/job/ci_linux/15634/)

**Comment by pablogs9** [comment]
What is the difference between mainline Foxy and `foxy` branch in this repo?

**Comment by jacobperron** [comment]
There's a lot that's changed since Foxy; I don't exactly know what difference is causing the test failure (it may not even be a change in this repository...). Sorry, I don't have the cycles at moment to dig into it.

**Comment by jacobperron** [comment]
I think I've resolved the test failures. The following PR seems to have fixed the issue: https://github.com/ros2/rmw_cyclonedds/pull/419

CI together with the connected PR:
- Linux [Build Status](https://ci.ros2.org/job/ci_linux/17294/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/11835/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/17781/)

**Review by jacobperron — APPROVED** [review]
I just need an a approval on the connected PR.

**Pull request merged**
