### PR TITLE
[eloquent] refactor regex for valid package/field names (#508)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #508 to Eloquent.

### CODE REVIEW

**Comment by jacobperron** [comment]
Testing `rosidl_adapter` and packages that recursively depend on it:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13205/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8136/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10921/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13223/)

**Comment by clalancette** [comment]
I have to say that I'm concerned about putting this change in right at the end of Eloquent's life.  While I know it fixes an issue, and it's been in Rolling for a while, regexes are tricky.  I just don't want to break an application that already works in Eloquent.

Is there a compelling bug report that has come in for Eloquent for us to make this change?

**Comment by jacobperron** [comment]
There's been no explicit bug report for Eloquent, but I suspect the original reported bug for Foxy (https://github.com/colcon/colcon-core/issues/364) also exists in Eloquent. FWIW, we've also backported this change to Dashing (https://github.com/ros2/rosidl/pull/549).

**Comment by clalancette** [comment]
> There's been no explicit bug report for Eloquent, but I suspect the original reported bug for Foxy ([colcon/colcon-core#364](https://github.com/colcon/colcon-core/issues/364)) also exists in Eloquent. 

Got it.

> FWIW, we've also backported this change to Dashing (#549).

Right.  It definitely makes sense for Dashing.  I'm more concerned about Eloquent, since we have no vehicle with which to fix it if we find a problem.

But I'm willing to be persuaded otherwise.  @mjcarroll thoughts?

**Comment by mjcarroll** [comment]
Yeah, I think I'm a little concerned dropping this one in without another sync/patch release on Eloquent.  I'll add it to known issues for Eloquent.

**Pull request closed without merging**
