### PR TITLE
Foxy backport hex constants and tab as whitespace support

### PR DESCRIPTION
**Pull request by dawonn**
These backports would help me publish a new ROS2 VectorNav hardware interface that I've developed for Foxy.

Thanks Again!

### CODE REVIEW

**Comment by clalancette** [comment]
@dawonn Please don't backport the release bump; foxy is on a different release branch with different numbering.

**Comment by dawonn** [comment]
Removed.

**Comment by dawonn** [comment]
Anything I can do to help push this along? I would like to release a driver with foxy support that depends on this.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13735/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8604/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11446/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13808/)

**Comment by clalancette** [comment]
None of the failed tests here seem to be because of this PR, so merging.

**Pull request merged**
