### PR TITLE
Type Description Nested Support

### PR DESCRIPTION
**Pull request by emersonknapp**
Part of ros2/ros2#1159

Bundled with (must be merged together):
* https://github.com/ros2/rosidl_typesupport/pull/141
* https://github.com/ros2/rosidl_typesupport_fastrtps/pull/101
* https://github.com/ros2/rmw_fastrtps/pull/680
* https://github.com/ros2/rmw_connextdds/pull/113
* https://github.com/ros2/rmw_cyclonedds/pull/448
* https://github.com/ros2/rcl/pull/1053

Replaces (or extends) ros2/rosidl#727. Key differences
* `type_support_t->get_type_hash_func` rather than bare value
* `get_type_description` and `get_type_sources` take a typesupport struct argument (for use by dynamic types)
* Type descriptions and sources include referenced types, rather than baking in full recursive dependencies per-interface
* Expected hashes of referenced types are included in codegen to optionally error-check with at runtime

Key features:
* Changes  `TYPE_HASH_TUPLES` to more accurate `TYPE_DESCRIPTION_TUPLES` in cmake
* Adds new C interface  functions `get_type_description`, `get_individual_type_description_source`,  and `get_type_description_sources`
* Implements above, generating code for type descriptions and raw interface definition sources, embedded in the binaries
* Optionally disables embedding that information in the generated code by the CMake flag `ROSIDL_GENERATOR_C_DISABLE_TYPE_DESCRIPTION_CODEGEN`
* Refactors `rosidl_generator_type_description` to output a new structure of `type_description_msg` plus a flat list of all referenced  types and their hashes at the time of generation. These hashes are used at runtime (in Debug builds) to detect  ABI breaks when constructing type descriptions the first time

### CODE REVIEW

**Comment by emersonknapp** [comment]
All working, including checking expected type hashes in asserts.
Still not implemented: type description raw sources

Sanity check

ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11744
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18392/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12938/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19073/)

**Comment by emersonknapp** [comment]
Wstring encoding problem:
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/19092/)

**Comment by emersonknapp** [comment]
`NDEBUG`-guard around hash value only used for `assert`
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18413/)

**Comment by emersonknapp** [comment]
Windows also needs to `open(encoding='utf-8')` explicitly:
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/19105/)

**Comment by clalancette** [comment]
@emersonknapp I'm a bit confused here; shouldn't we close this PR in favor of #727?

**Comment by emersonknapp** [comment]
Yes - I accidentally pushed that bugfix to the wrong branch

**Pull request closed without merging**
