### PR TITLE
enable access to all arrays

### PR DESCRIPTION
**Pull request by Karsten1987**
fixes ros2/rosidl#365
Signed-off-by: Karsten Knese <karsten@openrobotics.org>

### CODE REVIEW

**Comment by Karsten1987** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6784/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3084/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5579/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6611/)

**Comment by dirk-thomas** [comment]
These CI builds seem to only test the change from this repo. Since nothing is currently using these function pointers the test results don't say much. It would be more valuable to run tests with a code change which actually uses these to demonstrate they work as desired.

**Comment by Karsten1987** [comment]
new CI with testing `rosbag2` for generic message generation based on `rosidl_typesupport_introspection_cpp`:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6791/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3088/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5583/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6615/)

**Comment by Karsten1987** [comment]
windows CI for completeness: [Build Status](https://ci.ros2.org/job/ci_windows/6617/)

**Pull request merged**
