### PR TITLE
Fix warnings in Windows

### PR DESCRIPTION
**Pull request by ernestmc**
Connects to #60.

### CODE REVIEW

**Comment by ernestmc** [comment]
CI job:
* http://ci.ros2.org/job/ci_windows/878/

**Comment by esteve** [comment]
+1

**Comment by ernestmc** [comment]
Still getting warnings on int types. I'm changing to using the constants defined in the standard headers.

**Comment by ernestmc** [comment]
New job:
* http://ci.ros2.org/job/ci_windows/879/

**Comment by esteve** [comment]
+1 again :-)

**Pull request merged**
