### PR TITLE
Fix double free issue when initialization is failed

### PR DESCRIPTION
**Pull request by DongheeYe**
Fixes https://github.com/ros2/rosidl/issues/422

### CODE REVIEW

**Comment by allenh1** [comment]
This looks identical to #300. @clalancette do you know if there was a reason to change it to `destroy` instead of `fini`? Maybe a comment should be left above them so that this doesn't change back to `destroy` again?

I originally wrote `destroy` on those lines, but it should definitely be `fini`.

**Comment by clalancette** [comment]
> This looks identical to #300. @clalancette do you know if there was a reason to change it to `destroy` instead of `fini`? Maybe a comment should be left above them so that this doesn't change back to `destroy` again?
> 
> I originally wrote `destroy` on those lines, but it should definitely be `fini`.

For what it is worth, this didn't get changed back; the code that I fixed back in 2018 is still using `fini`.  In the meantime, new code got added that uses `destroy` instead of `fini` (commit 416ebd84a678178f8e8941a1961af8abe7514251, it looks like, which was all of the IDL refactoring, so its not surprising).

I guess we could add a comment, but it isn't clear to me where we would add it so that people would see it.

**Comment by clalancette** [comment]
Seems reasonable to me.  I'll kick-off CI on this, running the communication tests and some message packages just to make sure things generate properly.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8788/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4609/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7200/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8707/)

**Comment by clalancette** [comment]
All right, this is looking good to me, so I'm going to go ahead and merge.  Thanks for the contribution!

**Comment by jpsamper2009** [comment]
@dirk-thomas We could cherry-pick this fix into the dashing branch? Thanks!

**Comment by clalancette** [comment]
I've opened up https://github.com/ros2/rosidl/pull/426 and https://github.com/ros2/rosidl/pull/427 to backport this to Dashing and Eloquent.

**Pull request merged**
