### PR TITLE
Use target output name for exporting typesupport library

### LINKED ISSUE #623: Exporting typesupport libraries does not respect LIBRARY_NAME
## Bug report

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - ros-foxy-rosidl-typesupport-fastrtps-c: 1.0.4-1focal.20210901.175719
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Have one package that builds libraries passing in the LIBRARY_NAME variable, have a second that depends on that package and attempts to use the messages.

message package CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.5)
project(make_msgs)
find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
rosidl_generate_interfaces(${PROJECT_NAME}_msgs
        msg/CustomMessage.msg
        LIBRARY_NAME ${PROJECT_NAME}
        )
ament_package()
```

depending package CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.5)
project(depend_msgs)
find_package(ament_cmake REQUIRED)
find_package(make_msgs REQUIRED)
ament_package()
```

Build packages with colcon.

#### Expected behavior

Both package should compile successfully

#### Actual behavior

The depend_msgs package will fail with

```
--- stderr: depend_msgs                         
CMake Error at /testing/ros2/install/make_msgs/share/make_msgs/cmake/rosidl_cmake_export_typesupport_libraries-extras.cmake:26 (message):
  Package 'make_msgs' exports the typesupport library
  'make_msgs_msgs__rosidl_typesupport_fastrtps_c' which couldn't be found
Call Stack (most recent call first):
  /testing/ros2/install/make_msgs/share/make_msgs/cmake/make_msgsConfig.cmake:41 (include)
  CMakeLists.txt:4 (find_package)


---
Failed   <<< depend_msgs [0.34s, exited with code 1]
```

#### Additional information

Checking the `rosidl_cmake_export_typesupport_libraries-extras.cmake` file, the issue is present with the cpp version as well.

This probably does not affect only the fastrtps implementations, but as this is the default rmw for Foxy it is where I ran into the issue.

### PR DESCRIPTION
**Pull request by jonselling**
Fixes #623

### CODE REVIEW

**Review by aprotyas — APPROVED** [review]

**Comment by aprotyas** [comment]
Looks like the Rpr failure is unrelated. It happened in the last PR too.

**Comment by jonselling** [comment]
I had the issue when testing locally, I think it was due to ament_cmake_core not having a file in master that is present in the foxy branch

**Comment by clalancette** [comment]
The Rpr job will be fixed once we merge https://github.com/ros/rosdistro/pull/31089

**Comment by jonselling** [comment]
Is there a way for me to kick off another build since that PR was merged? I looked on Jenkins with no "Build Now" button or anything.

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by jonselling** [comment]
Seems like I jumped the gun on the PR merging in vs. getting into testing (I was unfamiliar with the release process and looked into it a little). I can kick off another build when the packages are in testing.

**Comment by clalancette** [comment]
> Seems like I jumped the gun on the PR merging in vs. getting into testing (I was unfamiliar with the release process and looked into it a little). I can kick off another build when the packages are in testing.

Ah yeah, I didn't check.  Because `desktop` didn't get built (see https://github.com/ros2/ros_buildfarm_config/blob/ros2/rolling/release-build.yaml#L20), sync-to-testing wasn't done.  I believe this will be fixed by https://github.com/ros/rosdistro/pull/31106

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by jonselling** [comment]
@aprotyas Is this waiting on anything else?

Also, I assumed it was fine if I signed off on the commit or does it need to be a maintainer? The contributing document said all commits needed to be signed off

**Comment by aprotyas** [comment]
> @aprotyas Is this waiting on anything else?

Just need to run CI, which I can do shortly.

> Also, I assumed it was fine if I signed off on the commit or does it need to be a maintainer?

Yeah, just the former is okay. It looks like you've signed the commit already.

---

Running CI.
Repos file: https://gist.githubusercontent.com/aprotyas/207c62d108174aa8e303cea2ad41c794/raw/53f225a72f0c60a937c6a451d83d9ab8af2d1c2f/ros2.repos
Build args: `--packages-above-and-dependencies rosidl_cmake`
Test args: `--packages-above rosidl_cmake`
Job: https://ci.ros2.org/job/ci_launcher/9294/

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15555/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10239/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13223/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15769/)

**Comment by clalancette** [comment]
Nightly Windows seems to be green, so I've kicked off another Windows build to make sure it goes green here.

**Comment by aprotyas** [comment]
Hmm, even more failures this time around... again, every failed test seems to be of the "exit gracefully"/"finite time-limit" type. No further insights.

**Comment by jonselling** [comment]
It looks like CI passed that time

**Comment by jonselling** [comment]
@aprotyas anything else?

**Comment by aprotyas** [comment]
CC @hidmic requesting your review since you were involved in the initial discussion over at #623.

**Review by hidmic — APPROVED** [review]
LGTM @jonselling!

**Comment by hidmic** [comment]
@jonselling we can now open a backport PR to Foxy or Galactic if you need so.

**Comment by aprotyas** [comment]
@mergify backport galactic foxy

**Comment by aprotyas** [comment]
Opened backports for consideration in both distros since this was a bug.

**Pull request merged**
