### PR TITLE
Fast-forward foxy branch

### PR DESCRIPTION
**Pull request by jacobperron**
I think all code changes, except #493, are marked for backport. I don't see why we shouldn't backport #493 either.

### CODE REVIEW

**Comment by jacobperron** [comment]
Note, there are no test failures. The Fpr job is failing due to an unrelated infrastructure issue.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please (using custom job config from ros-infrastructure/ros_buildfarm#828)

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please (using custom job config from ros-infrastructure/ros_buildfarm#828)

**Comment by jacobperron** [comment]
I've also add #514 to backport, though not strictly necessary I thought it would be nice to release once from `master` for both rolling and foxy.

**Pull request merged**
