### PR TITLE
Fixes #26

### LINKED ISSUE #26: [rosidl_generator_c] fails on static array of non-primitive type

### PR DESCRIPTION
**Pull request by ernestmc**
Separeted in two conditions for when the static array type is primitive and when it's a complex one.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Instead of replicating the whole line can you please make the type argument a local variable, set it to either of the two values and then call the macro in a single line.

Also wrapped lines need to be indented. For the print usually up to the opening parenthesis of the previous line.

**Comment by ernestmc** [comment]
@dirk-thomas I modified the code according to your comments. Please check if it's ok.

**Comment by wjwwood** [comment]
@ernestmc The changes look good to me.

We usually to CI jobs to verify our changes before merge. Unfortunately we can currently only do this if the branch in question is on the upstream repository (this one). So please push your branch to this repo and then:

- go to ci.ros2.org
- login (it will login using GitHub)
- go to the Linux CI job and do run with parameters
- then put the branch name in as the "test branch" option

After you've started the job, get the link to it and post it here.

Once we've seen that your changes pass CI, we can merge this pull request and delete the branch you created on this repository. In the future please push your proposed changes to a branch on the repository in question (rather than using your fork) so that it is easier to test.

I know this is different from how the workflow normally works on GitHub, but until our CI jobs can handle testing forks, we'll have to do it this way.

**Comment by dirk-thomas** [comment]
It looks good. Please run the tests of this package - I think the linter will warn about one style problem.

**Comment by wjwwood** [comment]
And as @dirk-thomas just pointed out, please run our test suite locally before starting CI jobs, so we can avoid wasting time on the build farm (blocking other CI jobs).

**Comment by ernestmc** [comment]
No errors running the local tests:
```
ament test src/ros2/rosidl/rosidl_generator_c

Install the project...
-- Install configuration: ""
-- Installing: /home/ecorbellini/repos/osrf/ros2_ws/install/lib/python3.4/site-packages/rosidl_generator_c
-- Installing: /home/ecorbellini/repos/osrf/ros2_ws/install/share/rosidl_generator_c/cmake
-- Installing: /home/ecorbellini/repos/osrf/ros2_ws/install/share/rosidl_generator_c/resource
-- Installing: /home/ecorbellini/repos/osrf/ros2_ws/install/include
-- Installing: /home/ecorbellini/repos/osrf/ros2_ws/install/include/rosidl_generator_c
Running tests...
UpdateCTestConfiguration  from :/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/DartConfiguration.tcl
Test project /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: copyright

1: Test command: /usr/bin/python3 "-u" "/home/ecorbellini/repos/osrf/ros2_ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/copyright.xml" "--output-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/ament_copyright/copyright.txt" "--command" "/home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_copyright" "--xunit-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/copyright.xml"
1: Test timeout computed to be: 60
1: -- run_test.py: invoking following command in '/home/ecorbellini/repos/osrf/ros2_ws/src/ros2/rosidl/rosidl_generator_c':
1:  - /home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_copyright --xunit-file /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/copyright.xml
1: No errors, checked 6 files
1: -- run_test.py: return code 0
1: -- run_test.py: verify result file '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/copyright.xml'
1/6 Test #1: copyright ........................   Passed    0.21 sec
test 2
    Start 2: cppcheck

2: Test command: /usr/bin/python3 "-u" "/home/ecorbellini/repos/osrf/ros2_ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/cppcheck.xml" "--output-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/ament_cppcheck/cppcheck.txt" "--command" "/home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_cppcheck" "--xunit-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/cppcheck.xml"
2: Test timeout computed to be: 60
2: -- run_test.py: invoking following command in '/home/ecorbellini/repos/osrf/ros2_ws/src/ros2/rosidl/rosidl_generator_c':
2:  - /home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_cppcheck --xunit-file /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/cppcheck.xml
2: No errors
2: -- run_test.py: return code 0
2: -- run_test.py: verify result file '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/cppcheck.xml'
2/6 Test #2: cppcheck .........................   Passed    0.23 sec
test 3
    Start 3: lint_cmake

3: Test command: /usr/bin/python3 "-u" "/home/ecorbellini/repos/osrf/ros2_ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/lint_cmake.xml" "--output-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/ament_lint_cmake/lint_cmake.txt" "--command" "/home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_lint_cmake" "--xunit-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/lint_cmake.xml"
3: Test timeout computed to be: 60
3: -- run_test.py: invoking following command in '/home/ecorbellini/repos/osrf/ros2_ws/src/ros2/rosidl/rosidl_generator_c':
3:  - /home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_lint_cmake --xunit-file /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/lint_cmake.xml
3: 
3: No errors
3: -- run_test.py: return code 0
3: -- run_test.py: verify result file '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/lint_cmake.xml'
3/6 Test #3: lint_cmake .......................   Passed    0.20 sec
test 4
    Start 4: pep8

4: Test command: /usr/bin/python3 "-u" "/home/ecorbellini/repos/osrf/ros2_ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/pep8.xml" "--output-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/ament_pep8/pep8.txt" "--command" "/home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_pep8" "--xunit-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/pep8.xml"
4: Test timeout computed to be: 60
4: -- run_test.py: invoking following command in '/home/ecorbellini/repos/osrf/ros2_ws/src/ros2/rosidl/rosidl_generator_c':
4:  - /home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_pep8 --xunit-file /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/pep8.xml
4: directory .
4: directory ./cmake
4: directory ./rosidl_generator_c
4: checking ./rosidl_generator_c/__init__.py
4: directory ./bin
4: directory ./include
4: directory ./include/rosidl_generator_c
4: directory ./resource
4: 
4: No errors or warnings
4: -- run_test.py: return code 0
4: -- run_test.py: verify result file '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/pep8.xml'
4/6 Test #4: pep8 .............................   Passed    0.20 sec
test 5
    Start 5: pyflakes

5: Test command: /usr/bin/python3 "-u" "/home/ecorbellini/repos/osrf/ros2_ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/pyflakes.xml" "--output-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/ament_pyflakes/pyflakes.txt" "--command" "/home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_pyflakes" "--xunit-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/pyflakes.xml"
5: Test timeout computed to be: 60
5: -- run_test.py: invoking following command in '/home/ecorbellini/repos/osrf/ros2_ws/src/ros2/rosidl/rosidl_generator_c':
5:  - /home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_pyflakes --xunit-file /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/pyflakes.xml
5: rosidl_generator_c/__init__.py
5: 
5: No errors
5: -- run_test.py: return code 0
5: -- run_test.py: verify result file '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/pyflakes.xml'
5/6 Test #5: pyflakes .........................   Passed    0.22 sec
test 6
    Start 6: uncrustify

6: Test command: /usr/bin/python3 "-u" "/home/ecorbellini/repos/osrf/ros2_ws/install/share/ament_cmake_test/cmake/run_test.py" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/uncrustify.xml" "--output-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/ament_uncrustify/uncrustify.txt" "--command" "/home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_uncrustify" "--xunit-file" "/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/uncrustify.xml"
6: Test timeout computed to be: 60
6: -- run_test.py: invoking following command in '/home/ecorbellini/repos/osrf/ros2_ws/src/ros2/rosidl/rosidl_generator_c':
6:  - /home/ecorbellini/repos/osrf/ros2_ws/install/bin/ament_uncrustify --xunit-file /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/uncrustify.xml
6: No code style divergence in file 'include/rosidl_generator_c/arrays.h'
6: 
6: No code style divergence in file 'include/rosidl_generator_c/message_type_support.h'
6: 
6: No code style divergence in file 'include/rosidl_generator_c/service_type_support.h'
6: 
6: No code style divergence in file 'include/rosidl_generator_c/visibility_control.h'
6: 
6: No errors
6: -- run_test.py: return code 0
6: -- run_test.py: verify result file '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/test_results/rosidl_generator_c/uncrustify.xml'
6/6 Test #6: uncrustify .......................   Passed    0.22 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) =   1.29 sec
# Topological order
 - rosidl_generator_c

Process package 'rosidl_generator_c' with context:
--------------------------------------------------------------------------------
 source_space => /home/ecorbellini/repos/osrf/ros2_ws/src/ros2/rosidl/rosidl_generator_c
  build_space => /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c
install_space => /home/ecorbellini/repos/osrf/ros2_ws/install
   make_flags => -j4, -l4
  build_tests => True
--------------------------------------------------------------------------------
+++ Building 'rosidl_generator_c'
==> '. /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/cmake__build.sh && /usr/bin/make cmake_check_build_system' in '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c'
==> '. /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/cmake__build.sh && /usr/bin/make -j4 -l4' in '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c'
+++ Installing 'rosidl_generator_c'
==> '. /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/cmake__install.sh && /usr/bin/make install' in '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c'
+++ Testing 'rosidl_generator_c'
==> '. /home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c/cmake__test.sh && /usr/bin/make test ARGS="-V"' in '/home/ecorbellini/repos/osrf/ros2_ws/build/rosidl_generator_c'
```

**Comment by ernestmc** [comment]
Pushed branch https://github.com/ros2/rosidl/tree/issue_26 and started the CI job http://ci.ros2.org/job/ros2_batch_ci_linux/582/

**Comment by dirk-thomas** [comment]
The template itself can't be linted. You can try to run our linters (e.g. `ament_cpplint`, `ament_uncrustify`) on some of the expanded templates.

**Comment by ernestmc** [comment]
I runned ament_uncrustify on the expanded C templates and it's only complaining on the length of some lines. I tried it on the cpp headers and it's also complaining on this.
```
Code style divergence in file 'bounded_array_bounded__struct.h':

--- bounded_array_bounded__struct.h
+++ bounded_array_bounded__struct.h.uncrustify
@@ -16 +16,2 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__BoundedArrayBounded, primitive_values, PrimitivesBounded, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__BoundedArrayBounded, primitive_values,
+  PrimitivesBounded, 3);

Code style divergence in file 'bounded_array_static__struct.h':

--- bounded_array_static__struct.h
+++ bounded_array_static__struct.h.uncrustify
@@ -16 +16,2 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__BoundedArrayStatic, primitive_values, PrimitivesStatic, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__BoundedArrayStatic, primitive_values,
+  PrimitivesStatic, 3);

Code style divergence in file 'bounded_array_unbounded__struct.h':

--- bounded_array_unbounded__struct.h
+++ bounded_array_unbounded__struct.h.uncrustify
@@ -16 +16,2 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__BoundedArrayUnbounded, primitive_values, PrimitivesUnbounded, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__BoundedArrayUnbounded, primitive_values,
+  PrimitivesUnbounded, 3);

Code style divergence in file 'primitive_static_arrays__struct.h':

--- primitive_static_arrays__struct.h
+++ primitive_static_arrays__struct.h.uncrustify
@@ -16 +16,2 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, byte_value, uint8_t, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, byte_value, uint8_t,
+  3);
@@ -18,10 +19,20 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, float32_value, float, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, float64_value, double, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, int8_value, int8_t, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, uint8_value, uint8_t, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, int16_value, int16_t, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, uint16_value, uint16_t, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, int32_value, int32_t, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, uint32_value, uint32_t, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, int64_value, int64_t, 3);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, uint64_value, uint64_t, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, float32_value, float,
+  3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, float64_value,
+  double, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, int8_value, int8_t,
+  3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, uint8_value, uint8_t,
+  3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, int16_value, int16_t,
+  3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, uint16_value,
+  uint16_t, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, int32_value, int32_t,
+  3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, uint32_value,
+  uint32_t, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, int64_value, int64_t,
+  3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitiveStaticArrays, uint64_value,
+  uint64_t, 3);

Code style divergence in file 'primitives_bounded__struct.h':

--- primitives_bounded__struct.h
+++ primitives_bounded__struct.h.uncrustify
@@ -18,2 +18,4 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, float32_value, float, 10);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, float64_value, double, 10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, float32_value, float,
+  10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, float64_value, double,
+  10);
@@ -21,7 +23,14 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, uint8_value, uint8_t, 10);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, int16_value, int16_t, 10);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, uint16_value, uint16_t, 10);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, int32_value, int32_t, 10);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, uint32_value, uint32_t, 10);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, int64_value, int64_t, 10);
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, uint64_value, uint64_t, 10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, uint8_value, uint8_t,
+  10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, int16_value, int16_t,
+  10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, uint16_value, uint16_t,
+  10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, int32_value, int32_t,
+  10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, uint32_value, uint32_t,
+  10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, int64_value, int64_t,
+  10);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__PrimitivesBounded, uint64_value, uint64_t,
+  10);

Code style divergence in file 'static_array_bounded__struct.h':

--- static_array_bounded__struct.h
+++ static_array_bounded__struct.h.uncrustify
@@ -16 +16,2 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__StaticArrayBounded, primitive_values, PrimitivesBounded, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__StaticArrayBounded, primitive_values,
+  PrimitivesBounded, 3);

Code style divergence in file 'static_array_static__struct.h':

--- static_array_static__struct.h
+++ static_array_static__struct.h.uncrustify
@@ -16 +16,2 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__StaticArrayStatic, primitive_values, PrimitivesStatic, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__StaticArrayStatic, primitive_values,
+  PrimitivesStatic, 3);

Code style divergence in file 'static_array_unbounded__struct.h':

--- static_array_unbounded__struct.h
+++ static_array_unbounded__struct.h.uncrustify
@@ -16 +16,2 @@
-ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__StaticArrayUnbounded, primitive_values, PrimitivesUnbounded, 3);
+ROSIDL_GENERATE_STATIC_ARRAY(rosidl_generator_cpp__msg__StaticArrayUnbounded, primitive_values,
+  PrimitivesUnbounded, 3);

8 files with code style divergence
No code style divergence in file 'bounded_array_bounded.h'

No code style divergence in file 'bounded_array_static.h'

No code style divergence in file 'bounded_array_unbounded.h'

No code style divergence in file 'empty.h'

No code style divergence in file 'empty__struct.h'

No code style divergence in file 'primitive_static_arrays.h'

No code style divergence in file 'primitives_bounded.h'

No code style divergence in file 'primitives_static.h'

No code style divergence in file 'primitives_static__struct.h'

No code style divergence in file 'primitives_unbounded.h'

No code style divergence in file 'primitives_unbounded__struct.h'

No code style divergence in file 'static_array_bounded.h'

No code style divergence in file 'static_array_static.h'

No code style divergence in file 'static_array_unbounded.h'

No code style divergence in file 'unbounded_array_bounded.h'

No code style divergence in file 'unbounded_array_bounded__struct.h'

No code style divergence in file 'unbounded_array_static.h'

No code style divergence in file 'unbounded_array_static__struct.h'

No code style divergence in file 'unbounded_array_unbounded.h'

No code style divergence in file 'unbounded_array_unbounded__struct.h'
```

**Comment by wjwwood** [comment]
@ernestmc If you want you can wrap those macros into multiline calls in the template (so they're shorter in the generated output), but I don't think that's necessary. Otherwise I think the linting looks good.

**Comment by wjwwood** [comment]
@ernestmc I'm gonna start the other CI jobs and if they pass, I think this is good to merge:

- http://ci.ros2.org/job/ros2_batch_ci_osx/469/
- http://ci.ros2.org/job/ros2_batch_ci_windows/633/ (opensplice)
- http://ci.ros2.org/job/ros2_batch_ci_windows/634/ (connext static)
- http://ci.ros2.org/job/ros2_batch_ci_windows/635/ (connext dynamic)

**Comment by wjwwood** [comment]
+1, It looks like CI tests passed. @ernestmc make any last minute changes you think are needed (and rerun CI if you think they are needed) and merge when you think it's ready.

**Pull request merged**
