### PR TITLE
Always include whitespace in string literals

### LINKED ISSUE #676: rosidl_generator_c does not produce replicable generated files
**Required Info:**
- Operating System:
  - Ubuntu 20.04
- Installation type:
  - Binaries
- Version or commit hash:
  - main
- DDS implementation:
  - Fast DDS
- Client library (if applicable):
  - N/A

#### Steps to reproduce the issue

Pull and run a ROS 2 Rolling Docker env:

```bash
docker pull ros:rolling
docker run -it --rm ros:rolling
```

Inside the docker prepare a sample environment:

```
apt update
apt upgrade -y
source /opt/ros/rolling/setup.bash
mkdir -p ws/src && cd ws
git clone -b master https://github.com/ros2/common_interfaces src/common_interfaces
cp -r src/common_interfaces/actionlib_msgs/ src
rm -rf src/common_interfaces/
```

Build and check file output multiple times with:

```bash
rm -rf build/ install/ log/ && colcon build --packages-select actionlib_msgs > /dev/null 2>&1 && md5sum install/actionlib_msgs/include/actionlib_msgs/actionlib_msgs/msg/detail/goal_status__struct.h && md5sum install/actionlib_msgs/share/actionlib_msgs/msg/GoalStatus.idl 
```

As seen below, the generated IDL file is always the same but the header files are modified for each build:

```
#1 
f6d011ce1a542d883a3bd23a6664b2ea  install/actionlib_msgs/include/actionlib_msgs/actionlib_msgs/msg/detail/goal_status__struct.h
cd9baf779987f38a9b7cb07d8a952a09  install/actionlib_msgs/share/actionlib_msgs/msg/GoalStatus.idl
#2 
eaf75edc414175000b168954b5d885fe  install/actionlib_msgs/include/actionlib_msgs/actionlib_msgs/msg/detail/goal_status__struct.h
cd9baf779987f38a9b7cb07d8a952a09  install/actionlib_msgs/share/actionlib_msgs/msg/GoalStatus.idl
#3
a2d2b8acfcbdfe937a94373cb2b65f4e  install/actionlib_msgs/include/actionlib_msgs/actionlib_msgs/msg/detail/goal_status__struct.h
cd9baf779987f38a9b7cb07d8a952a09  install/actionlib_msgs/share/actionlib_msgs/msg/GoalStatus.idl
#4
0029b7956254bd3560bebe99c81663cd  install/actionlib_msgs/include/actionlib_msgs/actionlib_msgs/msg/detail/goal_status__struct.h
cd9baf779987f38a9b7cb07d8a952a09  install/actionlib_msgs/share/actionlib_msgs/msg/GoalStatus.idl
#5
c02b65a4261a540d0b8d598245015fbc  install/actionlib_msgs/include/actionlib_msgs/actionlib_msgs/msg/detail/goal_status__struct.h
cd9baf779987f38a9b7cb07d8a952a09  install/actionlib_msgs/share/actionlib_msgs/msg/GoalStatus.idl
```

#### Expected behavior

Generated code is always the same for every iteration.

#### Actual behavior

Generated code randomly modifies spaces and indentation along with runs.

#### Additional information

It seems to be something related to spaces and indentation:

image

### PR DESCRIPTION
**Pull request by sloretz**
Alternative to #677 
Fixes #676 

`rosidl_parser` randomly ignores whitespace at the start of string literals. This example matches the string literal as `Token('__ANON_6', '    e')` or `Token('__ANON_6', 'e')` when run multiple times; however, stripping the whitespace is incorrect.

```python3
from rosidl_parser.parser import get_ast_from_idl_string

idl_str ='''module MRE {
const string foo = "    e";
};'''
print(get_ast_from_idl_string(idl_str))
```

I think the cause is a combination of ignoring whitespace

https://github.com/ros2/rosidl/blob/0250ae85e442485fd438451f88f60cbcf65088fd/rosidl_parser/rosidl_parser/grammar.lark#L18

and the way the `string_literal` rule is constructed

https://github.com/ros2/rosidl/blob/0250ae85e442485fd438451f88f60cbcf65088fd/rosidl_parser/rosidl_parser/grammar.lark#L77

The `string_literal` rule has two parts. The first part matches an empty string `""`, and the second part matches a non-empty string. The second part says to match three things. First match a quote `"`. Next match at least one of: an escaped quote `\"`, or a character that is not a quote. Finally match another quote `"`.  I think the problem is the second rule being divided into three parts. It ambiguous if the parser should ignore the whitespace between the first quote and the string content, or if it should include the whitespace via the not-a-quote regex.

Lark has a built in rule for exactly this situation: https://github.com/lark-parser/lark/blob/953171821ed307f700fddf27f3fcb9483346bd46/lark/grammars/common.lark#L26-L29

We could `%import common.ESCAPED_STRING` for `string_literal`, but `whide_string_literal` probably has the same problem. If I defined `wide_string_literal` as `"L" ESCAPED_STRING` then it would also match `L     "white space between L and first quote"`, which is also incorrect. I've chosen to copy the rules from lark into our grammar instead.

There's a stackoverlow post explaining how lark's `ESCAPED_STRING` rule works: https://stackoverflow.com/a/61374198

### CODE REVIEW

**Comment by sloretz** [comment]
@pablogs9 this seems to resolve the issue on my machine. Mind checking if it works for your use case?

**Comment by pablogs9** [comment]
@sloretz LGTM, thanks a lot for this.

Are you goint to backport to humble?

**Comment by sloretz** [comment]
I added tests for whitespace at the start and end of the string. With `rolling` as it is before this PR I only see the whitespace at the start of the string and wide string tests fail. I left the whitespace at the end of the string tests in since there's no harm in testing it. All tests pass with this PR.

**Comment by sloretz** [comment]
> Are you going to backport to humble?

I think this change is backportable to humble.

**Comment by sloretz** [comment]
CI (build: `--packages-above-and-dependencies rosidl_parser` test: `--packages-above rosidl_parser`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16949/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11514/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17348/)

**Comment by sloretz** [comment]
Linux CI failure is known to be flaky: ros2/rosbag2#862. CI LGTM!

**Review by wjwwood — APPROVED** [review]
lgtm

code changes are arcane, but the test cases make sense to me.

+1 for backporting, if anyone was relying on this behavior it was a bug and therefore I think it's ok to break them.

**Comment by sloretz** [comment]
@mergifyio backport humble galactic foxy

**Pull request merged**
