### PR TITLE
Add types to rosidl_cli

### PR DESCRIPTION
**Pull request by InvincibleRMC**

### CODE REVIEW

**Review by sloretz — APPROVED** [review]

**Comment by sloretz** [comment]
@mergifyio update

**Comment by sloretz** [comment]
Pulls: https://github.com/ros2/rosidl/pull/826
Gist: https://gist.githubusercontent.com/sloretz/fc71d0aad0686a7a81376fbb32e57add/raw/59674849538b9c82b25472c1440de2e3e072fd98/ros2.repos
BUILD args:  --packages-up-to rosidl_cli
TEST args:  --packages-select rosidl_cli
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14627
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21908/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16176/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1419/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22629/)

**Comment by sloretz** [comment]
Mind adding `<test_depend>ament_mypy</test_depend>` to the `package.xml`?

```
ImportError while importing test module '/home/jenkins-agent/workspace/ci_linux/ws/src/InvincibleRMC/rosidl/rosidl_cli/test/test_mypy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_mypy.py:15: in <module>
    from ament_mypy.main import main
E   ModuleNotFoundError: No module named 'ament_mypy'
```

**Comment by InvincibleRMC** [comment]
> Mind adding `<test_depend>ament_mypy</test_depend>` to the `package.xml`?
> 
> ```
> ImportError while importing test module '/home/jenkins-agent/workspace/ci_linux/ws/src/InvincibleRMC/rosidl/rosidl_cli/test/test_mypy.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /usr/lib/python3.12/importlib/__init__.py:90: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> test/test_mypy.py:15: in <module>
>     from ament_mypy.main import main
> E   ModuleNotFoundError: No module named 'ament_mypy'
> ```

oops. Will do

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21909/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16177/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1420/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22630/)

**Comment by InvincibleRMC** [comment]
@fujitatomoya I have address the errors. should be re-runnable now.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21911/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16179/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1422/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22632/)

**Comment by InvincibleRMC** [comment]
@fujitatomoya I made a change to fix the Windows error.

**Comment by InvincibleRMC** [comment]
@fujitatomoya This CI should be ready to re-run.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21941/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16208/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1458/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22668/)

**Comment by InvincibleRMC** [comment]
I see I misunderstood the error but, it should be resolved now.

**Comment by fujitatomoya** [comment]
https://github.com/ros2/rosidl/pull/826/commits/cc29d8a1e9afc1f16493a5538d24991353e30b5a should fix the mypy failure.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21942/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16209/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1459/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22669/)

**Review by ahcorde — APPROVED** [review]

**Comment by clalancette** [comment]
This PR is causing regressions on Windows: https://ci.ros2.org/view/nightly/job/nightly_win_rel/3191/testReport/junit/(root)/projectroot/test_cli_extension/

Specifically, the code in https://github.com/ros2/rosidl/pull/826/files#diff-6867a0a0c2e4946ffe6fadc04c32c1e9362a9518bac9ca31629c7276d198a13cR24-R58 is not a direct replacement for what was there before (because it was overriding `specs`, that variable was always guaranteed to exist).

I'm going to propose a revert PR here.

**Comment by InvincibleRMC** [comment]
Ah I see. I missed setting a default for `specs_set`.

**Comment by fujitatomoya** [comment]
@ahcorde @InvincibleRMC @clalancette 

sorry about this.

I will make sure to run test CI with all dependent packages, it should have been able to detect this `UnboundLocalError`.

**Pull request merged**
