### PR TITLE
Move rosidl_typesupport_introspection_c quality declaration to Q1 

### PR DESCRIPTION
**Pull request by j-rivero**
With the latest changes in the repository, we are pushing the quality level in `rosidl_typesupport_introspection_c` to Q1.

@hidmic I left the justification of the lack performance testing in this repo to you :)

### CODE REVIEW

**Comment by hidmic** [comment]
@j-rivero PTAL. I took the liberty to improve all testing related sections.

**Comment by j-rivero** [comment]
> @j-rivero PTAL. I took the liberty to improve all testing related sections.

Thanks, it is great.

**Review by clalancette — APPROVED** [review]

**Comment by hidmic** [comment]
Cool! Now we need one for `rosidl_typesupport_introspection_cpp` :)

**Comment by j-rivero** [comment]
> Cool! Now we need one for `rosidl_typesupport_introspection_cpp` :)

I go for it.

**Pull request merged**
